### ISSUE TITLE
Storing multiplex indices/values in the same storage

### ISSUE THREAD

**Issue by nockawa** [VictorScherbakov/DataTanker#1]
First: impressive work, congratulation!

I'd like to use the library to store a variable amount of indices, of different key/value types.
I understand I could create one storage per index, but that would lead to three files stored on the disk, so I would have 3 _x_ files for _x_ indices.
If I could get a way to store everything in just three files I believe it would be better.

Please advise, I'd be happy to contribute if I have some insights and if the workload/complexity is not too high.

I'm willing to convert the library in .Net Standart 2.0, I've run the portability analyzer, there's a 100% match, so it's only a matter of project structure change.

Another remark, I've profiled the lib during the 100K random alloc in your WinForm application and there's a considerable amount of time spent in `RecoveryFile.EnsureFileExists()` for the check if the file already exist, if we avoid this we can drop 10% on the `Set()` method.

**Comment by VictorScherbakov** [comment]
Thanks for the feedback!

1. Storing multiple indexes in one fileset is a nice idea.
But for now it looks like a very large task requiring a lot work and testing.

I think, this can be done in several stages:

- Design the on-disk structures for schema (index names, types etc.) 
In the current implementation, the storage heading page contains only a single pointer to the first index page.

- Make the storage engine able to handle requests to a specific index.

- Add these features to the external storage interface. Here we most likely not be able to maintain backward compatibility.

This is a very schematic way that does not reflect details. It needs to be decomposed to simpler tasks.

2. Porting to .Net Standard looks much easier. And it's great that the analyzer did not detect compatibility issues.

3. Thanks a lot for RecoveryFile.EnsureFileExists() issue. This would be a very simple and effective fix.

As for items 2 and 3 - your changes are welcome.
