### ISSUE TITLE
Disposing recoveryFile when a member variable

### ISSUE THREAD

**Issue by tomwolfgang** [VictorScherbakov/DataTanker#13]
https://github.com/VictorScherbakov/DataTanker/blob/1c77b9667433aa929d5b0b925b17830165c34b40/DataTanker/Core/PageManagement/FileSystemPageManager.cs#L644

When a member variable, if you dispose the member, it will throw exceptions when trying to Flush.

Thanks

**Comment by tomwolfgang** [comment]
I also recommend wrapping the |_flushTimer.Elapsed| timer with a try ... catch ... - because when the storage is corrupted, I constantly get an "Index out of bound" exception.

**Comment by VictorScherbakov** [comment]
> https://github.com/VictorScherbakov/DataTanker/blob/1c77b9667433aa929d5b0b925b17830165c34b40/DataTanker/Core/PageManagement/FileSystemPageManager.cs#L644
> 
> When a member variable, if you dispose the member, it will throw exceptions when trying to Flush.
> 
> Thanks

Sure, member variable check should be inverted. Thank you!



> I also recommend wrapping the |_flushTimer.Elapsed| timer with a try ... catch ... - because when the storage is corrupted, I constantly get an "Index out of bound" exception.

Could you provide an example of a corrupted storage to reproduce the case? Or (even better) make a pull request with this fix by yourself.
