### ISSUE TITLE
pagemap size

### ISSUE THREAD

**Issue by tomwolfgang** [VictorScherbakov/DataTanker#16]
Hi,
I have a lot of rewrites of the same key-value in my software.
I see that the pagemap file grows each time I finish a cycle of such updates.

When does it shrink? If at all?

Thanks

**Comment by VictorScherbakov** [comment]
Hi, 
This file never shrinks and grows slowly. But it allows the main storage file to be shrinked instead, and makes an empty spaces (holes after deletions) reusable.

**Comment by tomwolfgang** [comment]
Ok, thanks
