### ISSUE TITLE
Incorrect uses of CompareTo

### ISSUE THREAD

**Issue by RealDolos** [VictorScherbakov/DataTanker#5]
I am modifying a copy of DataTanker right now[*] and noticed that in a few places the code calls `obj.CompareTo(other) == 1` (`== -1`, `!= 1` and so on).
The contract for this method however states it will return less-than-zero, zero, greater-than-zero, not -1, 0, 1, as the DataTanker code currently assumes.

Indeed, if I were to implement a custom key type, e.g. using `StringComparer.Ordinal` (or anything that does `return a.length - b.Length`), then stuff breaks, horribly.

I'd therefore suggest to fix this bug by inspecting all uses of `.CompareTo()`

[*] Not that it matters for the issue at hand, but I modded it to remove ComparableKeyOf, KeyOf, ValueOf (in favor of nullable types if you really need it), and to provide a way for custom IComparer's instead of relying on keys to implement IComparable, which does allow me to use e.g. byte[] keys.

**Comment by VictorScherbakov** [comment]
Thank you very much!

You've identified a really significant problem that has been missed for a long time.
