### ISSUE TITLE
FSPageManager default buffering considered harmful

### ISSUE THREAD

**Issue by RealDolos** [VictorScherbakov/DataTanker#6]
Before I forget, I looked into the performance characteristics quite a lot and one easy and rather impactful improvement was to change the FileSystemPageManager buffer defaults.

Right now, it defaults to `writeBufferSize * PageSize`, where `writeBufferSize` defaults to `100`, or worse `1000` when constructed via `StorageFactory` with caching enabled and default cache settings.

https://github.com/VictorScherbakov/DataTanker/blob/master/DataTanker/Core/PageManagement/FileSystemPageManager.cs#L727

https://github.com/VictorScherbakov/DataTanker/blob/master/DataTanker/Core/StorageFactory.cs#L337

i.e. given a default `4096` page size, the usual case is `1000 * 4096 = 4096000` passed to the `FileStream` as the preferred buffer size.

Given that page access is extremely random during normal operation (as is a result of B+/Radix trees), the probability that two successive reads are close enough to each other that the seek to the next requested page offset does not discard the file streams internal buffer (and uninterrupted by writes, which would also discard writes) is extremely low. That means most of the time (almost always for a lot of work loads) the file stream buffer is discarded after being used to read only a single page. But the buffer was filled with 1000 pages, 999 of which are never accessed before being discard, creating a lot of useless disk I/O.

I have a real world program that was read-only at 65k page size

**Unmodified**:
 - 678 `FetchPage`s
 - 676 disk I/O `ReadFile`s of `65536000` bytes each, meaning 2 reads were served from the buffer which is a hit rate of `0.3%`.
 - Total disk reads: `44302336000 bytes` = `41.26 GiB`
 - ufff (thanks to the OS disk cache, it wasn't this many hard reads, thankfully).

**Modified** to use `writeBufferSize = 1`:
 - 678 `FetchPage`s,
 - 678 disk I/O `ReadFile`s of `65536` bytes each (obviously)
 - Total disk reads: `44433408 bytes` = `0.04 GiB`
 - Now that's more like it.

The difference is a whooping `41 GiB` in `ReadFile` requests to the OS. Of course, the larger the page size, the worse it gets.

**Conclusion**

Given the low probability that the file streams buffer will be useful, I recommend to chose `writeBufferSize = 1` for all defaults.

**Comment by VictorScherbakov** [comment]
Looks like a very nice improvement.

Yep... in normal cases, there is no need to set up a FileStream with buffer size larger than the page size.

Even if we don’t take into account the FileStream allocates an additional buffer...
It seems that a bufferSized chunk of a file is read in any way (unless we reach EOF), even if one byte is requested.
https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/filestream.cs#L1526

That's why you've seen such a bad I/O statistics:

> 676 disk I/O ReadFiles of **65536000** bytes **each**.

Many thanks for the contribution!
